title: Benjamin Mbonyimana # your name (or website title) here
logo: "/images/89771937_1008008266267058_9115681302480158720_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Studies Information and Communication Technology at KTH Royal Institute of Technology 
  <br><br>
  <br><br>
  E-mail: bmb@kth.se 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
