title: Benjamin Mbonyimana # your name (or website title) here
logo: "/images/89771937_1008008266267058_9115681302480158720_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Full name: Benjamin Jansson Mbonyimana
  <br><br>
  Date of birth: 26 February 1998 (age 22)
  <br><br>
  Studies Information and Communication Technology at KTH Royal Institute of Technology in Stockholm.  
  <br><br>
  Familiar with Java, C, Elixir and Prolog.
  <br><br>
  E-mail: bmb@kth.se
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
